'use client'

import { useMemo, useState } from 'react'
import { ArrowLeft, Check, Copy, Eye, FileImage, Filter, Grid2X2, ImagePlus, List, Search, Upload, X } from 'lucide-react'

const assets = [
  { name: 'hero-editorial-01', type: 'Image', size: '2.4 MB', tag: 'Homepage', src: '/hero-fashion.png' },
  { name: 'indigo-lookbook', type: 'Image', size: '1.8 MB', tag: 'Collection', src: '/product-indigo.png' },
  { name: 'heritage-collection', type: 'Image', size: '2.1 MB', tag: 'Collection', src: '/collection-heritage.png' },
  { name: 'robe-ko-detail', type: 'Image', size: '1.2 MB', tag: 'Catalogue', src: '/product-indigo.png' },
  { name: 'sac-nzassa-campaign', type: 'Image', size: '980 KB', tag: 'Campagne', src: '/collection-heritage.png' },
  { name: 'atelier-abidjan', type: 'Image', size: '1.6 MB', tag: 'Story', src: '/hero-fashion.png' },
]

export default function MediaPage() {
  const [query, setQuery] = useState('')
  const [view, setView] = useState<'grid' | 'list'>('grid')
  const [selected, setSelected] = useState<string | null>(null)
  const [uploaded, setUploaded] = useState(false)
  const filtered = useMemo(() => assets.filter((asset) => `${asset.name} ${asset.tag}`.toLowerCase().includes(query.toLowerCase())), [query])
  const selectedAsset = assets.find((asset) => asset.name === selected)

  return (
    <main className="min-h-screen bg-[#f7f4ef] text-[#171512]">
      <header className="border-b border-black/[.08] bg-white/75 px-5 py-5 backdrop-blur md:px-10"><div className="mx-auto flex max-w-[1380px] items-center justify-between"><a href="/admin" className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-[#1b3d54]"><ArrowLeft className="size-4" /> Dashboard</a><p className="font-display text-2xl">Revizit<span className="text-[#d39a54]">.</span></p><a href="/" className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-[#b85b3c]"><Eye className="size-4" /> Boutique</a></div></header>
      <div className="mx-auto max-w-[1380px] px-5 py-10 md:px-10">
        <div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="text-[10px] font-bold uppercase tracking-[.22em] text-[#b85b3c]">Bibliothèque média</p><h1 className="mt-2 font-display text-5xl tracking-[-.04em]">Les images qui racontent.</h1><p className="mt-3 max-w-xl text-sm leading-6 text-black/50">Centralisez les visuels de Revizit et réutilisez-les dans vos produits, collections et campagnes.</p></div><button onClick={() => { setUploaded(true); window.setTimeout(() => setUploaded(false), 2400) }} className="flex items-center justify-center gap-2 rounded-full bg-[#b85b3c] px-5 py-3 text-xs font-bold uppercase tracking-widest text-white shadow-lg shadow-[#b85b3c]/20"><Upload className="size-4" /> {uploaded ? 'Import terminé' : 'Importer des médias'}</button></div>
        <div className="mt-9 flex flex-col gap-4 rounded-2xl border border-black/[.07] bg-white/70 p-4 md:flex-row md:items-center md:justify-between"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-black/35" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Rechercher un visuel ou un tag..." className="w-full rounded-xl border border-black/10 bg-white/70 py-3 pl-10 pr-4 text-sm outline-none transition focus:border-[#b85b3c]" /></div><div className="flex items-center gap-2"><button className="flex items-center gap-2 rounded-xl border border-black/10 px-4 py-3 text-xs font-bold uppercase tracking-wider"><Filter className="size-4" /> Filtrer</button><div className="flex rounded-xl border border-black/10 p-1"><button onClick={() => setView('grid')} className={`rounded-lg p-2 ${view === 'grid' ? 'bg-[#1b3d54] text-white' : 'text-black/40'}`} aria-label="Vue grille"><Grid2X2 className="size-4" /></button><button onClick={() => setView('list')} className={`rounded-lg p-2 ${view === 'list' ? 'bg-[#1b3d54] text-white' : 'text-black/40'}`} aria-label="Vue liste"><List className="size-4" /></button></div></div></div>
        <div className="mt-6 flex items-center justify-between"><p className="text-xs text-black/45">{filtered.length} médias · Dernière synchronisation aujourd&apos;hui</p><p className="flex items-center gap-2 text-xs text-emerald-700"><span className="size-2 rounded-full bg-emerald-500" /> Stockage opérationnel</p></div>
        {view === 'grid' ? <div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{filtered.map((asset) => <button key={asset.name} onClick={() => setSelected(asset.name)} className="group overflow-hidden rounded-2xl border border-black/[.07] bg-white/75 text-left transition hover:-translate-y-1 hover:shadow-xl hover:shadow-black/5"><div className="relative aspect-[1.15] overflow-hidden bg-[#e9e2d8]"><img src={asset.src} alt={asset.name} className="size-full object-cover transition duration-500 group-hover:scale-105" /><span className="absolute left-3 top-3 rounded-full bg-white/85 px-2.5 py-1 text-[9px] font-bold uppercase tracking-wider">{asset.tag}</span></div><div className="p-4"><p className="truncate text-sm font-semibold">{asset.name}</p><p className="mt-1 text-xs text-black/40">{asset.type} · {asset.size}</p></div></button>)}</div> : <div className="mt-4 overflow-hidden rounded-2xl border border-black/[.07] bg-white/75"><div className="grid grid-cols-[1fr_120px_120px_40px] gap-4 border-b border-black/[.07] px-5 py-3 text-[10px] font-bold uppercase tracking-widest text-black/40"><span>Nom</span><span>Tag</span><span>Taille</span><span /></div>{filtered.map((asset) => <button key={asset.name} onClick={() => setSelected(asset.name)} className="grid w-full grid-cols-[1fr_120px_120px_40px] items-center gap-4 border-b border-black/[.06] px-5 py-4 text-left text-sm last:border-0 hover:bg-black/[.02]"><span className="flex items-center gap-3 font-semibold"><img src={asset.src} alt="" className="size-10 rounded-lg object-cover" /><span className="truncate">{asset.name}</span></span><span className="text-xs text-black/50">{asset.tag}</span><span className="text-xs text-black/50">{asset.size}</span><FileImage className="size-4 text-black/35" /></button>)}</div>}
      </div>
      {selectedAsset && <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#171512]/45 p-5" onClick={() => setSelected(null)}><div className="w-full max-w-lg rounded-3xl bg-[#f7f4ef] p-5 shadow-2xl" onClick={(event) => event.stopPropagation()}><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#b85b3c]">Aperçu du média</p><h2 className="mt-1 font-display text-2xl">{selectedAsset.name}</h2></div><button onClick={() => setSelected(null)} className="rounded-full p-2 hover:bg-black/5" aria-label="Fermer"><X className="size-5" /></button></div><img src={selectedAsset.src} alt={selectedAsset.name} className="mt-5 aspect-video w-full rounded-2xl object-cover" /><div className="mt-4 flex items-center justify-between text-xs text-black/50"><span>{selectedAsset.type} · {selectedAsset.size}</span><button className="flex items-center gap-2 font-bold uppercase tracking-wider text-[#1b3d54]"><Copy className="size-4" /> Copier le lien</button></div></div></div>}
    </main>
  )
}
