'use client'

import Image from 'next/image'
import Link from 'next/link'
import { motion } from 'framer-motion'

const collections = [{ title: 'Héritage', text: 'Indigo, terre cuite et gestes transmis.', image: '/hero-fashion.png' }, { title: 'Lagune', text: 'Une palette fraîche, libre et solaire.', image: '/product-indigo.png' }, { title: 'Objets du quotidien', text: 'Des accessoires faits pour durer.', image: '/collection-heritage.png' }]

export default function CollectionsPage() { return <main className="min-h-screen bg-[var(--paper)] text-[var(--ink)]"><header className="mx-auto flex max-w-[1320px] items-center justify-between px-5 py-6 md:px-10"><Link href="/" className="font-display text-2xl">Revizit<span className="text-[var(--rust)]">.</span></Link><Link href="/" className="text-xs font-bold uppercase tracking-[.18em]">Accueil</Link></header><section className="mx-auto max-w-[1320px] px-5 pb-16 pt-10 md:px-10"><motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }}><p className="text-[10px] font-bold uppercase tracking-[.25em] text-[var(--rust)]">Explorer par histoire</p><h1 className="mt-3 font-display text-5xl leading-[.95] tracking-[-.04em] md:text-7xl">Nos <i className="font-normal text-[var(--rust)]">collections.</i></h1><p className="mt-5 max-w-md text-sm leading-6 text-black/55">Chaque collection est une conversation entre notre héritage et la vie contemporaine.</p></motion.div><div className="mt-12 grid gap-5 md:grid-cols-3">{collections.map((item, index) => <motion.div key={item.title} initial={{ opacity: 0, y: 26 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .12 }} className="group relative min-h-[390px] overflow-hidden rounded-[26px]"><Image src={item.image} alt={item.title} fill className="object-cover transition duration-700 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-black/75 via-black/10 to-transparent" /><div className="absolute inset-x-5 bottom-5 text-white"><h2 className="font-display text-3xl">{item.title}</h2><p className="mt-1 text-xs text-white/70">{item.text}</p><Link href="/arrivages" className="mt-4 inline-flex text-[10px] font-bold uppercase tracking-widest">Découvrir →</Link></div></motion.div>)}</div></section></main> }
