'use client'

import { useState } from 'react'
import { ArrowLeft, Check, ChevronRight, Clock3, MapPin, Plus, Truck } from 'lucide-react'

const zones = [
  { name: 'Abidjan intra-muros', detail: 'Cocody, Marcory, Plateau, Yopougon', price: '2 500 FCFA', eta: '24 à 48 h', active: true },
  { name: 'Grand Abidjan', detail: 'Bingerville, Anyama, Songon', price: '3 500 FCFA', eta: '48 à 72 h', active: true },
  { name: 'Autres villes', detail: 'Bouaké, Yamoussoukro, San-Pédro', price: '5 000 FCFA', eta: '3 à 5 jours', active: true },
]

export default function LivraisonsPage() {
  const [express, setExpress] = useState(true)
  return <main className="min-h-screen bg-[#f7f4ef] text-[#171512]">
    <header className="border-b border-black/[.08] bg-white/70 px-5 py-5 md:px-10"><div className="mx-auto flex max-w-[1380px] items-center justify-between"><a href="/admin" className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-[#1b3d54]"><ArrowLeft className="size-4"/> Dashboard</a><p className="font-display text-2xl">Revizit<span className="text-[#d39a54]">.</span></p><span className="rounded-full bg-[#1b3d54]/[.08] px-3 py-1 text-[10px] font-bold uppercase tracking-widest text-[#1b3d54]">Opérations</span></div></header>
    <div className="mx-auto max-w-[1380px] px-5 py-10 md:px-10"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-[10px] font-bold uppercase tracking-[.22em] text-[#b85b3c]">Logistique ivoirienne</p><h1 className="mt-2 font-display text-5xl tracking-[-.04em]">Livraisons.</h1><p className="mt-3 max-w-xl text-sm leading-6 text-black/50">Définissez des zones simples, transparentes et adaptées à vos clientes.</p></div><button className="flex items-center justify-center gap-2 rounded-full bg-[#b85b3c] px-5 py-3 text-xs font-bold uppercase tracking-widest text-white"><Plus className="size-4"/> Ajouter une zone</button></div>
      <div className="mt-9 grid gap-4 md:grid-cols-3">{[['Livraisons en cours','18','Aujourd\'hui'],['Délai moyen','2,4 jours','-0,6 jour'],['Satisfaction','96,8 %','+4,2 %']].map(([label,value,trend])=><article key={label} className="rounded-2xl border border-black/[.07] bg-white/70 p-6"><p className="text-xs text-black/45">{label}</p><p className="mt-4 font-display text-3xl">{value}</p><p className="mt-2 text-xs font-semibold text-emerald-700">{trend}</p></article>)}</div>
      <div className="mt-6 grid gap-6 xl:grid-cols-[1fr_.65fr]"><section className="rounded-2xl border border-black/[.07] bg-white/70 p-6 md:p-8"><div className="mb-6 flex items-center justify-between"><div><h2 className="font-display text-2xl">Zones & tarifs</h2><p className="mt-1 text-xs text-black/45">Les options proposées au checkout.</p></div><Truck className="size-5 text-[#b85b3c]"/></div><div className="flex flex-col gap-3">{zones.map(zone=><div key={zone.name} className="flex flex-col gap-4 rounded-xl border border-black/[.07] bg-white/60 p-4 sm:flex-row sm:items-center"><div className="flex size-10 items-center justify-center rounded-full bg-[#d39a54]/20 text-[#1b3d54]"><MapPin className="size-4"/></div><div className="min-w-0 flex-1"><p className="font-semibold">{zone.name}</p><p className="mt-1 truncate text-xs text-black/45">{zone.detail}</p></div><div className="flex items-center gap-5 text-right"><div><p className="text-sm font-bold">{zone.price}</p><p className="mt-1 text-[10px] text-black/40">{zone.eta}</p></div><span className="flex size-7 items-center justify-center rounded-full bg-emerald-100 text-emerald-700"><Check className="size-4"/></span></div></div>)}</div></section><section className="rounded-2xl bg-[#1b3d54] p-6 text-white md:p-8"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#d39a54]">Options de livraison</p><h2 className="mt-3 font-display text-3xl">Un choix clair,<br/><i className="font-normal text-white/60">sans surprise.</i></h2><div className="mt-8 flex flex-col gap-4"><div className="flex items-center gap-3 border-b border-white/10 pb-4"><Clock3 className="size-5 text-[#d39a54]"/><div className="flex-1"><p className="text-sm font-semibold">Livraison express</p><p className="mt-1 text-xs text-white/45">Le jour même à Abidjan</p></div><button onClick={()=>setExpress(!express)} className={`h-6 w-11 rounded-full p-1 transition ${express?'bg-[#d39a54]':'bg-white/20'}`} aria-label="Activer la livraison express"><span className={`block size-4 rounded-full bg-white transition ${express?'translate-x-5':''}`}/></button></div><p className="text-xs leading-5 text-white/50">Les frais sont affichés avant paiement. Le retrait en boutique reste toujours gratuit.</p><button className="mt-2 flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-[#d39a54]">Configurer les transporteurs <ChevronRight className="size-4"/></button></div></section></div>
    </div></main>
}

