'use client'

import Image from 'next/image'
import Link from 'next/link'
import { motion } from 'framer-motion'

const products = [{ name: 'Robe Kô', category: 'Vêtements', price: '89 000 FCFA', image: '/hero-fashion.png' }, { name: 'Ensemble Sassandra', category: 'Vêtements', price: '125 000 FCFA', image: '/product-indigo.png' }, { name: 'Sac N’Zassa', category: 'Accessoires', price: '48 000 FCFA', image: '/collection-heritage.png' }]

export default function BoutiquePage() { return <main className="min-h-screen bg-[var(--paper)] text-[var(--ink)]"><header className="mx-auto flex max-w-[1320px] items-center justify-between px-5 py-6 md:px-10"><Link href="/" className="font-display text-2xl">Revizit<span className="text-[var(--rust)]">.</span></Link><Link href="/" className="text-xs font-bold uppercase tracking-[.18em]">Accueil</Link></header><section className="mx-auto max-w-[1320px] px-5 pb-16 pt-10 md:px-10"><motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }}><p className="text-[10px] font-bold uppercase tracking-[.25em] text-[var(--rust)]">La sélection Revizit</p><h1 className="mt-3 font-display text-5xl leading-[.95] tracking-[-.04em] md:text-7xl">La <i className="font-normal text-[var(--rust)]">boutique.</i></h1></motion.div><div className="mt-10 flex flex-wrap gap-2"><button className="rounded-full bg-[var(--ink)] px-4 py-2 text-[10px] font-bold uppercase tracking-widest text-white">Tout voir</button>{['Vêtements', 'Accessoires', 'Maison'].map((filter) => <button key={filter} className="rounded-full border border-black/10 px-4 py-2 text-[10px] font-bold uppercase tracking-widest transition hover:bg-white">{filter}</button>)}</div><div className="mt-8 grid gap-5 sm:grid-cols-2 md:grid-cols-3">{products.map((item, index) => <motion.article key={item.name} initial={{ opacity: 0, y: 22 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .1 }} className="group"><div className="relative aspect-[4/5] overflow-hidden rounded-[26px] bg-[var(--cobalt)]"><Image src={item.image} alt={item.name} fill className="object-cover transition duration-700 group-hover:scale-105" /></div><div className="flex justify-between gap-3 pt-4"><div><h2 className="font-display text-xl">{item.name}</h2><p className="mt-1 text-xs text-black/50">{item.category}</p></div><p className="text-xs font-bold">{item.price}</p></div></motion.article>)}</div></section></main> }
