'use client'

import { useState } from 'react'
import Image from 'next/image'
import { ArrowRight, Heart, Menu, Search, ShoppingBag, Sparkles, X } from 'lucide-react'

const products = [
  { name:'Robe Kô', detail:'Coton tissé · Indigo', price:'89 000 FCFA', image:'/hero-fashion.png', tag:'Édition limitée' },
  { name:'Ensemble Sassandra', detail:'Lin & bazin · Terre cuite', price:'125 000 FCFA', image:'/product-indigo.png', tag:'Nouveau' },
  { name:'Sac N’Zassa', detail:'Cuir végétal · Fait main', price:'48 000 FCFA', image:'/collection-heritage.png', tag:'Artisan local' },
]

export default function Home() {
  const [cart, setCart] = useState(0), [menu, setMenu] = useState(false), [liked, setLiked] = useState<number[]>([])
  return <main className="min-h-screen overflow-hidden bg-[var(--paper)]">
    <div className="bg-[var(--cobalt)] px-5 py-2 text-center text-[10px] font-bold uppercase tracking-[.25em] text-white">Livraison offerte à Abidjan dès 75 000 FCFA <span className="mx-2 text-[var(--gold)]">✦</span> Paiement Wave disponible</div>
    <header className="relative z-20 mx-auto flex max-w-[1320px] items-center justify-between px-5 py-6 md:px-10">
      <button aria-label="Menu" onClick={()=>setMenu(!menu)} className="flex size-10 items-center justify-center rounded-full border border-black/10 md:hidden">{menu?<X/>:<Menu/>}</button>
      <a className="font-display text-3xl font-semibold tracking-tight">nia<span className="text-[var(--rust)]">.</span></a>
      <nav className={`${menu?'flex':'hidden'} absolute left-4 right-4 top-20 flex-col gap-5 rounded-2xl bg-[var(--ink)] p-6 text-white md:static md:flex md:flex-row md:items-center md:bg-transparent md:p-0 md:text-[var(--ink)]`}><a href="#shop" className="text-xs font-bold uppercase tracking-[.18em]">La boutique</a><a href="#story" className="text-xs font-bold uppercase tracking-[.18em]">Notre histoire</a><a href="#journal" className="text-xs font-bold uppercase tracking-[.18em]">Le journal</a></nav>
      <div className="flex items-center gap-2"><button aria-label="Rechercher" className="hidden size-10 items-center justify-center rounded-full border border-black/10 md:flex"><Search/></button><button aria-label="Panier" onClick={()=>setCart(cart+1)} className="relative flex size-10 items-center justify-center rounded-full bg-[var(--ink)] text-white"><ShoppingBag/><span className="absolute -right-1 -top-1 flex size-4 items-center justify-center rounded-full bg-[var(--rust)] text-[9px] font-bold">{cart}</span></button></div>
    </header>
    <section className="mx-auto grid max-w-[1320px] gap-8 px-5 pb-20 md:grid-cols-[1.05fr_.95fr] md:items-center md:px-10 md:pb-32">
      <div className="relative z-10 pt-10 md:pt-20"><p className="mb-7 flex items-center gap-3 text-[11px] font-bold uppercase tracking-[.3em] text-[var(--rust)]"><span className="size-2 rounded-full bg-[var(--rust)]"/> Collection 01 · Héritage</p><h1 className="font-display max-w-[700px] text-[clamp(4rem,8vw,8rem)] leading-[.84] tracking-[-.055em]">L&apos;Afrique<br/><i className="font-normal text-[var(--rust)]">en mouvement.</i></h1><p className="mt-8 max-w-[420px] text-base leading-7 text-black/60">Des pièces qui racontent nos terres, nos gestes et celles et ceux qui les font vivre. La mode ivoirienne, autrement.</p><a href="#shop" className="mt-9 inline-flex items-center gap-4 rounded-full bg-[var(--rust)] px-7 py-4 text-xs font-bold uppercase tracking-[.18em] text-white transition-transform hover:scale-105">Découvrir la collection <ArrowRight/></a></div>
      <div className="relative mt-6 h-[520px] md:h-[680px]"><div className="absolute inset-4 rotate-3 rounded-[48%_48%_12%_12%] bg-[var(--gold)]/30 md:inset-10"/><div className="relative h-full overflow-hidden rounded-[48%_48%_12%_12%] bg-[var(--cobalt)]"><Image src="/hero-fashion.png" fill priority className="object-cover object-center mix-blend-luminosity opacity-90 transition-transform duration-700 hover:scale-105" alt="Modèle portant une création Nia"/></div><div className="drift absolute -bottom-3 -left-4 flex size-28 rotate-[-12deg] items-center justify-center rounded-full bg-[var(--gold)] text-center text-[10px] font-bold uppercase leading-4 tracking-widest text-[var(--ink)] md:-left-8">Fait<br/>en Côte<br/>d&apos;Ivoire</div><div className="absolute right-0 top-12 rounded-full border border-white/40 bg-white/15 px-4 py-2 text-[10px] font-bold uppercase tracking-widest text-white backdrop-blur">01 / 03</div></div>
    </section>
    <div className="overflow-hidden border-y border-black/10 bg-[var(--cream)] py-4"><div className="marquee-track flex w-max gap-10 whitespace-nowrap text-[11px] font-bold uppercase tracking-[.3em]">{Array.from({length:8},(_,i)=><span key={i} className="flex items-center gap-10">Design conscient <b className="text-[var(--rust)]">✦</b> Créé en Côte d&apos;Ivoire <b className="text-[var(--rust)]">✦</b></span>)}</div></div>
    <section id="shop" className="mx-auto max-w-[1320px] px-5 py-24 md:px-10 md:py-32"><div className="mb-12 flex items-end justify-between"><div><p className="mb-4 text-[11px] font-bold uppercase tracking-[.25em] text-[var(--rust)]">La sélection</p><h2 className="font-display text-5xl tracking-[-.04em] md:text-7xl">Pièces <i className="font-normal">singulières.</i></h2></div><a href="#shop" className="hidden items-center gap-2 text-xs font-bold uppercase tracking-widest md:flex">Tout voir <ArrowRight/></a></div><div className="grid gap-6 md:grid-cols-3">{products.map((p,i)=><article key={p.name} className="group"><div className="relative aspect-[.82] overflow-hidden rounded-[28px] bg-[var(--cream)]"><Image src={p.image} fill className="object-cover transition duration-700 group-hover:scale-105" alt={p.name}/><span className="absolute left-4 top-4 rounded-full bg-[var(--paper)] px-3 py-2 text-[10px] font-bold uppercase tracking-widest">{p.tag}</span><button onClick={()=>setLiked(liked.includes(i)?liked.filter(x=>x!==i):[...liked,i])} aria-label="Ajouter aux favoris" className="absolute right-4 top-4 flex size-10 items-center justify-center rounded-full bg-[var(--paper)] transition hover:scale-110"><Heart className={liked.includes(i)?'fill-[var(--rust)] text-[var(--rust)]':''}/></button><button onClick={()=>setCart(cart+1)} className="absolute bottom-4 left-4 right-4 translate-y-16 rounded-full bg-[var(--ink)] py-4 text-xs font-bold uppercase tracking-widest text-white opacity-0 transition-all duration-300 group-hover:translate-y-0 group-hover:opacity-100">Ajouter au panier</button></div><div className="flex items-start justify-between pt-5"><div><h3 className="font-display text-2xl">{p.name}</h3><p className="mt-1 text-sm text-black/50">{p.detail}</p></div><p className="text-sm font-bold">{p.price}</p></div></article>)}</div></section>
    <section id="story" className="relative overflow-hidden bg-[var(--cobalt)] px-5 py-24 text-white md:px-10 md:py-32"><div className="noise absolute inset-0"/><div className="relative mx-auto grid max-w-[1320px] items-center gap-12 md:grid-cols-[.8fr_1.2fr]"><div><Sparkles className="mb-8 text-[var(--gold)]"/><p className="mb-5 text-[11px] font-bold uppercase tracking-[.25em] text-[var(--gold)]">Le geste avant la tendance</p><h2 className="font-display text-5xl leading-[.95] tracking-[-.04em] md:text-7xl">Porter une histoire.<br/><i className="font-normal text-[var(--gold)]">Pas un costume.</i></h2><p className="mt-8 max-w-md text-base leading-7 text-white/65">Nous travaillons avec des ateliers et des créateurs qui font de la matière un langage. Chaque pièce est pensée pour durer, évoluer et vous ressembler.</p><a href="#journal" className="mt-8 inline-flex items-center gap-3 text-xs font-bold uppercase tracking-widest text-[var(--gold)]">Notre manifeste <ArrowRight/></a></div><div className="relative aspect-[1.3] overflow-hidden rounded-[32px] md:rotate-2"><Image src="/collection-heritage.png" fill className="object-cover" alt="Artisan travaillant un textile"/></div></div></section>
    <footer id="journal" className="mx-auto flex max-w-[1320px] flex-col gap-8 px-5 py-12 md:flex-row md:items-center md:justify-between md:px-10"><div><p className="font-display text-3xl">nia<span className="text-[var(--rust)]">.</span></p><p className="mt-2 text-sm text-black/50">La mode, en héritage.</p></div><p className="text-xs uppercase tracking-widest text-black/40">© 2026 Nia Studio · Abidjan</p><div className="flex gap-5 text-xs font-bold uppercase tracking-widest"><a>Instagram</a><a>Contact</a></div></footer>
  </main>
}
